- name: demo on task level variables
  hosts: localhost
  connection: local
  vars:
    COURSE: "Ansible"
    TRAINER: "Shivakumar"
  tasks:
  - name: print information
    vars:
      COURSE: "DevSecops with AIOps"
    debug:
      msg: "Hi, I am learning {{ COURSE }}, Trainer is {{ TRAINER }}"
