- name: Demo on var_files
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print variable information
    debug:
      msg: "Hi, I am learning {{ COURSE }}, Trainer is {{ TRAINER }}"