- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: Linux, Shell, Ansible, Terraform
    tagMap:
      name: ansible
      project: roboshop
      environment: dev
  tasks:
  - name: convert string to list
    debug:
      msg: "Topics are : {{ topics | split(',')}}"

  - name: set default common_value
    debug:
      msg: "Hi {{ GREETING | default('Good Morning') }}"

  - name: convert map to list
    debug:
      msg: "{{ tagMap | dict2items }}"