- name: demo on error handling
  hosts: local
  connection: local
  tasks:
  - name: check roboshop user exist or not
    command: id roboshop
    register: user_output
    ignore_errors: true

  - name: print user_output
    debug:
      msg: "{{ user_output }}"

  - name: create user
    command: useradd roboshop
    when: user_output.rc != 0
