[frontend]
172.31.38.163 ;COURSE="Ansible for NODE-1" # These are called as individual host vars
;172.31.27.197 ;COURSE="Ansible for NODE-2"

[catalogue]
172.31.27.249


[user]
172.31.27.250

[cart]
172.31.27.251

; group of groups
[roboshop:children]
frontend
catalogue
user
cart

[local]
localhost

; local group vars
;  [local:vars]
;  COURSE="Ansible"
;  TRAINER="Sivakumar"
;  DURATION="10HRS"

; [frontend:vars]
; COURSE="Ansible"
; TRAINER="Sivakumar"
; DURATION="10HRS"